#!/bin/sh
set -e

cd ~

# Install Homebrew
if [ ! -f /opt/homebrew/bin/brew ] || [ ! -f /usr/local/bin/brew ]; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew already installed."
fi

# Clone my dotfiles
if [ ! -d ~/dotfiles ]; then
    cd ~/.ssh
    ssh-keygen
    pbcopy <~/.ssh/id_rsa.pub
    echo "公開鍵をGitHubに登録しましたか？"
    select yn in "Yes"; do
        case $yn in
        Yes) break ;;
        esac
    done

    echo "Cloning dotfiles..."
    git clone git@github.com:nemuki/dotfiles.git
else
    echo "dotfiles already cloned."
fi

Install some software
echo "Installing some software & library..."
brew bundle -v --file=./dotfiles/Brewfile

if [ ! -d ~/.config ]; then
    echo "Creating ~/.config directory..."
    mkdir ~/.config
fi

echo "zshの設定を読み込む"
source ~/.zshrc

echo "シンボリックリンクを貼る"
echo "Symlinking dotfiles..."
sh ~/dotfiles/shell/symlink && echo "Done."
