#!/bin/sh

set -e

cd "$HOME"

# Install Homebrew
if [ ! -e /opt/homebrew/bin/brew ] && [ ! -e /usr/local/bin/brew ]; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew already installed."
fi

# Clone my dotfiles
if [ ! -d "$HOME"/dotfiles ]; then
    echo "Clone dotfiles"
    git clone https://github.com/nemuki/dotfiles.git
else
    echo "dotfiles repo already installed."
fi

# Install some software
echo "Installing some software & library..."
brew bundle -v --file=~/dotfiles/Brewfile

if [ ! -d ~/.zsh/completions ]; then
    echo "Creating ~/.zsh/completions directory..."
    mkdir -p ~/.zsh/completions
    wget -P ~/.zsh/completions https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    wget -O ~/.zsh/completions/_git https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
fi

if [ ! -d ~/.config ]; then
    echo "Creating ~/.config directory..."
    mkdir ~/.config
fi

echo "zshの設定を読み込む"
. "$HOME/.zshrc"

echo "シンボリックリンクを貼る"
echo "Symlinking dotfiles..."
sh ~/dotfiles/shell/symlink

echo "fzf shell extensions not installed, install command↓"
echo "$(brew --prefix)/opt/fzf/install"

echo "done."